### ISSUE TITLE
Section with lnfaucet infos

### ISSUE THREAD

**Issue by fguisso** [decred/lightning-faucet#29]
Create a section with all information about the lnfaucet node:
- block height/hash
- decreds available
- pubkey@ip:port
- node alias

I started this here, but left before think it's not very useful [fguisso/info-list](https://github.com/fguisso/lightning-faucet/tree/info-list), reactivate with @davecgh suggestion.

anything else?

**Comment by davecgh** [comment]
Probably the faucet and lnd versions as well.

**Comment by matheusd** [comment]
Current block height and whether the faucet is `synced_to_graph`/`synced_to_chain`
